#########################################################
# Complete one of the following input data
# Remove the other lines if not needed
#########################################################

# Genbank accessions of assembly accession (GCA, GCF)
ids:
  - CP019090
  - CP019092
  - CP019085
  - GCA_001042775.1
  - GCA_001021915.1
  - GCA_022406815.1

# Path of genbank files
input_genbanks:
  - data/GCA_001518895.1.gb
  - data/GCA_001746615.1.gb
  - data/GCA_003382895.1.gb

# Input genomes as fasta and annotation files in GFF format
# Only applied when using Orthofinder or PGGB workflows
input_genomes:
  "GCA_001518895":
    "fasta": "data/GCA_001518895.1.fasta"
    "gff3": "data/GCA_001518895.1.gff3"
    "name": "Xoo_PXO83"
  "GCA_001746615":
    "fasta": "data/GCA_001746615.1.fasta"
    "gff3": "data/GCA_001746615.1.gff3" 
    "name": "Xoo_PXO145"
  "GCA_003382895":
    "fasta": "data/GCA_003382895.1.fasta"
    "gff3": "data/GCA_003382895.1.gff3"
    "name": "Xoo_PX079" 

